import { ROUTES } from "@/constants/routes";

export const GUEST_ONLY_ROUTES = [ROUTES.AUTH.LOGIN, ROUTES.AUTH.REGISTER];

export const CONTENT_MANAGE_ROUTES = [
  ROUTES.DASHBOARD.REKSADANA.CATEGORIES,
  ROUTES.DASHBOARD.REKSADANA.ITEMS,
  ROUTES.DASHBOARD.REKSADANA.RECORDS,
  // tambahkan route lain di sini
];

export const ADMIN_MANAGE_ROUTES = [ROUTES.DASHBOARD.SYSTEM.USERS];
