export const MOCK_STOCKS = [
  {
    symbol: "BBCA",
    name: "Bank Central Asia Tbk",
    price: 9800,
    change: 1.5,
    pe: 24.5,
    pbv: 4.8,
    sector: "Finance",
  },
  {
    symbol: "BBRI",
    name: "Bank Rakyat Indonesia (Persero) Tbk",
    price: 5600,
    change: -0.8,
    pe: 14.2,
    pbv: 2.6,
    sector: "Finance",
  },
  {
    symbol: "TLKM",
    name: "Telkom Indonesia (Persero) Tbk",
    price: 3200,
    change: 0.5,
    pe: 16.8,
    pbv: 2.9,
    sector: "Infrastructure",
  },
  {
    symbol: "ASII",
    name: "Astra International Tbk",
    price: 5100,
    change: 2.1,
    pe: 7.5,
    pbv: 1.1,
    sector: "Conglomerate",
  },
  {
    symbol: "UNVR",
    name: "Unilever Indonesia Tbk",
    price: 2800,
    change: -1.2,
    pe: 28.4,
    pbv: 18.2,
    sector: "Consumer Goods",
  },
];
